import type { Metadata } from "next";
import "../globals.css";
import { fonts } from "../utils/fonts";
import Logo from "@/components/Logo";
import MobileNav from "@/components/MobileNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts} text-black`}>{children}</body>
    </html>
  );
}
