import type { Metadata } from "next";
import "../globals.css";
import { fonts } from "../utils/fonts";
import Logo from "@/components/Logo";
import MobileNav from "@/components/MobileNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts} bg-notes-blue-third text-black`}>
        <header className="p-4">
          <Logo />
        </header>
        <main>{children}</main>
        <nav className="fixed bottom-0 left-0 flex w-screen items-center justify-center">
          <MobileNav />
        </nav>
      </body>
    </html>
  );
}
