import type { Metadata } from "next";
import "../globals.css";
import { fonts } from "../utils/fonts";
import Logo from "@/components/Logo";
import MobileNav from "@/components/navigation/MobileNav";
import DesktopNav from "@/components/navigation/DesktopNav";
import TitlePage from "@/components/TitlePage";
import IconSearch from "@/assets/images/icon-search.svg";
import IconSettings from "@/assets/images/icon-settings.svg";
import Image from "next/image";
import Link from "next/link";
import SearchNote from "@/components/SearchNote";
import connectDB from "@/config/database";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts} h-screen bg-white text-black`}>
        <div className="h-full w-full overflow-scroll bg-notes-blue-third xl:hidden">
          <header className="h-[10%] p-4">
            <Logo />
          </header>
          <main className="h-[80%] w-full rounded-t-2xl bg-white p-4 font-notes-interRegular">
            {children}
          </main>

          <nav className="flex h-[10%] w-screen items-center justify-center bg-white">
            <MobileNav />
          </nav>
        </div>
        <div className="h-screen bg-white xs:hidden xl:flex">
          <aside className="min-h-screen w-1/6 overflow-hidden border-r-[1px] p-2">
            <DesktopNav />
          </aside>
          <main className="flex w-5/6 flex-col">
            <header className="flex h-[13%] items-center justify-between border-b-[1px] p-5 px-8">
              <TitlePage />
              <div className="flex items-center gap-8">
                <SearchNote />
                <div>
                  <Link href="/settings">
                    <Image src={IconSettings} alt="" />
                  </Link>
                </div>
              </div>
            </header>
            <div className="h-[87%] w-full overflow-hidden">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
